engines:
  rubocop:
    enabled: true
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
  requiresafe:
    enabled: false
languages:
  JavaScript: true
#ratings:
#   paths:
#   - app/**
#   - "**.go"
exclude_paths:
- scripts/**/*
- conf/**/*
- architecture/**/*
- src/backend/**/*